### ISSUE TITLE
Can we have the ability to check previous versions?

### ISSUE THREAD

**Issue by Jordy19** [Epicpkmn11/HBChecker#2]
The script now is being updated to work with the latest version of the homebrew applications.
Can we implement a feature that asks us the version name of lets say HiyaCFW or TWLightMenu?

**How it can work**
It can be done with an separate JSON file which will contain the file tree of the versions. 
When starting up the script, the script can ask which version you installed and check the files for that version instead of the files of the last version. 

*Bonus: It would be fantastic to have a way to automatically detect the version of HiaCFW and TWLightMenu by scanning the SD-Card files.
I know that we can see the version of the NDS Bootstrap version in TWILightMenu++ by checking the release-bootstrap.ver file.*

**Comment by Epicpkmn11** [comment]
Check out the experimental branch I just made:
https://github.com/Epicpkmn11/DSi-HB-Checker/tree/experimental

I basically remade the whole thing, so now it checks what to load from another .py file (I might change the extension and have it read out of it instead to avoid confusion of which you should run), with the new changes it can be easily modified to have older versions by using different list files. This also makes it very flexible for other used than Hiya and TWiLight on DSi's and it could easily be expanded to other consoles with this.

I'll probably make this the new master version and do a release soon if I don't find any problems with it.

(Sorry for taking a while to notice this, GitHub wan't emailing me...)

**Comment by Jordy19** [comment]
That looks great!

**Comment by Epicpkmn11** [comment]
Are you able to test it on WIndows? I seems to be working fine on Mac, but I haven't been able to test windows

**Comment by Jordy19** [comment]
It works fine on Windows, just one question. Why are is the list in .py format? You can write it was .json format which will look better.

**Comment by Epicpkmn11** [comment]
With the last couple commits I switched it to json, I hadn't used that before so I wasn't sure how you do it, but I just looked it up and it was easy

**Comment by Jordy19** [comment]
Nice, good job! :)
